// MongoDB initialization script
// Runs automatically when the MongoDB container is created for the first time.
//
// Current project flow:
//
// Real EV Data + NOAA Weather
//          ↓
//     Apache Spark
//          ↓
// Spark MLlib Random Forest
//          ↓
//   predictions.json
//          ↓
//       MongoDB
//          ↓
//     Streamlit Dashboard

db = db.getSiblingDB('ev_charging');


// ─────────────────────────────────────────────────────────────────────────────
// Application User
// ─────────────────────────────────────────────────────────────────────────────

db.createUser({
  user: 'ev_app',
  pwd: 'ev_app_pass',
  roles: [
    {
      role: 'readWrite',
      db: 'ev_charging'
    }
  ]
});


// ─────────────────────────────────────────────────────────────────────────────
// Predictions Collection
// ─────────────────────────────────────────────────────────────────────────────
//
// This collection stores the prediction records generated by Spark MLlib.
//
// Example document:
//
// {
//   station_id: "BOULDER / AIRPORT ST1",
//   timestamp: "2023-01-13 11:00:00",
//   actual_demand: 1,
//   predicted_demand: 1.04,
//   total_ports: 4,
//   location_type: "urban",
//   model: "RandomForest",
//   created_at: "2026-10-06T05:10:54Z"
// }

db.createCollection('predictions');


// Search/filter predictions by station and time.
db.predictions.createIndex(
  {
    station_id: 1,
    timestamp: -1
  },
  {
    name: 'station_timestamp_idx'
  }
);


// Sort/filter predictions by timestamp.
db.predictions.createIndex(
  {
    timestamp: -1
  },
  {
    name: 'timestamp_idx'
  }
);


// Quickly find high-demand predictions.
db.predictions.createIndex(
  {
    predicted_demand: -1
  },
  {
    name: 'predicted_demand_idx'
  }
);


// Filter prediction records by model.
db.predictions.createIndex(
  {
    model: 1
  },
  {
    name: 'model_idx'
  }
);


// ─────────────────────────────────────────────────────────────────────────────
// Station Metadata Collection
// ─────────────────────────────────────────────────────────────────────────────
//
// The dashboard may generate fallback station metadata when the source
// dataset does not contain complete location/port information.

db.createCollection('station_metadata');

db.station_metadata.createIndex(
  {
    station_id: 1
  },
  {
    unique: true,
    name: 'station_id_unique_idx'
  }
);


// ─────────────────────────────────────────────────────────────────────────────
// Model Metrics Collection
// ─────────────────────────────────────────────────────────────────────────────
//
// Optional collection for storing model evaluation metrics such as:
// MAE, RMSE and R².

db.createCollection('model_metrics');

db.model_metrics.createIndex(
  {
    trained_at: -1
  },
  {
    name: 'trained_at_idx'
  }
);


// ─────────────────────────────────────────────────────────────────────────────
// Initialization Complete
// ─────────────────────────────────────────────────────────────────────────────

print('============================================================');
print('MongoDB EV Charging Analytics database initialized');
print('Database   : ev_charging');
print('Collection : predictions');
print('Model      : Spark MLlib Random Forest');
print('============================================================');