"""
mongo_loader.py
────────────────
Loads Spark MLlib prediction results from:

    data/processed/predictions.json
                ↓
             MongoDB
                ↓
           Streamlit

MongoDB:
    Database   : ev_charging
    Collection : predictions

The loader:
- Reads predictions generated by the Spark pipeline.
- Connects to MongoDB using MONGO_URI.
- Creates useful indexes.
- Removes the previous Random Forest prediction batch.
- Inserts the latest predictions.
- Verifies the inserted document count.
- Prints a sample document.
- Gracefully falls back to the JSON file if MongoDB is unavailable.
"""

import os
import json
import logging

from pymongo import MongoClient, ASCENDING, DESCENDING


# ─────────────────────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
)

log = logging.getLogger("MongoLoader")


# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

MONGO_URI = os.getenv(
    "MONGO_URI",
    "mongodb://admin:evpassword@localhost:27017/ev_charging?authSource=admin",
)

DB_NAME = os.getenv(
    "MONGO_DB",
    "ev_charging",
)

COLLECTION_NAME = os.getenv(
    "MONGO_COLLECTION",
    "predictions",
)

# Spark writes the prediction file here.
PRED_FILE = os.path.abspath(
    os.path.join(
        os.path.dirname(__file__),
        "..",
        "data",
        "processed",
        "predictions.json",
    )
)


# ─────────────────────────────────────────────────────────────────────────────
# Load Predictions
# ─────────────────────────────────────────────────────────────────────────────

def load_prediction_file():
    """
    Read predictions generated by the Spark MLlib pipeline.
    """

    if not os.path.exists(PRED_FILE):
        raise FileNotFoundError(
            f"""
Prediction file not found:

{PRED_FILE}

Run the Spark pipeline first so that predictions.json is generated.
"""
        )

    with open(
        PRED_FILE,
        "r",
        encoding="utf-8",
    ) as file:

        records = json.load(file)

    if not isinstance(records, list):
        raise ValueError(
            "predictions.json must contain a JSON list of prediction records."
        )

    if not records:
        raise ValueError(
            "predictions.json exists but contains no prediction records."
        )

    log.info(
        "Read %d prediction records from %s",
        len(records),
        PRED_FILE,
    )

    return records


# ─────────────────────────────────────────────────────────────────────────────
# MongoDB Loader
# ─────────────────────────────────────────────────────────────────────────────

def load_predictions_to_mongo():

    records = load_prediction_file()

    client = None

    try:

        # ─────────────────────────────────────────────────────────────────────
        # Connect to MongoDB
        # ─────────────────────────────────────────────────────────────────────

        log.info("Connecting to MongoDB...")

        client = MongoClient(
            MONGO_URI,
            serverSelectionTimeoutMS=3000,
        )

        # Force an immediate connection check.
        client.admin.command("ping")

        db = client[DB_NAME]
        collection = db[COLLECTION_NAME]

        log.info(
            "Connected to MongoDB database '%s', collection '%s'.",
            DB_NAME,
            COLLECTION_NAME,
        )

        # ─────────────────────────────────────────────────────────────────────
        # Create Indexes
        # ─────────────────────────────────────────────────────────────────────

        try:
            collection.create_index(
                [
                    ("station_id", ASCENDING),
                    ("timestamp", DESCENDING),
                ]
            )

            collection.create_index(
                [
                    ("timestamp", DESCENDING),
                ]
            )

            collection.create_index(
                [
                    ("predicted_demand", DESCENDING),
                ]
            )

            log.info("MongoDB indexes are ready.")
        except Exception as idx_err:
            log.warning("Index creation notice: %s", idx_err)

        # ─────────────────────────────────────────────────────────────────────
        # Remove Previous Prediction Batch
        # ─────────────────────────────────────────────────────────────────────

        deleted = collection.delete_many(
            {
                "model": "RandomForest",
            }
        )

        log.info(
            "Removed %d previous Random Forest prediction documents.",
            deleted.deleted_count,
        )

        # ─────────────────────────────────────────────────────────────────────
        # Insert Latest Predictions
        # ─────────────────────────────────────────────────────────────────────

        insert_result = collection.insert_many(
            records,
            ordered=False,
        )

        inserted_count = len(
            insert_result.inserted_ids
        )

        total_docs = collection.count_documents({})

        log.info(
            "Inserted %d prediction documents.",
            inserted_count,
        )

        log.info(
            "Total documents currently in '%s.%s': %d",
            DB_NAME,
            COLLECTION_NAME,
            total_docs,
        )

        # ─────────────────────────────────────────────────────────────────────
        # Retrieve Sample
        # ─────────────────────────────────────────────────────────────────────

        sample = collection.find_one(
            {},
            {
                "_id": 0,
            },
        )

        log.info(
            "Sample prediction document:\n%s",
            json.dumps(
                sample,
                indent=2,
                default=str,
            ),
        )

        return total_docs, sample

    except Exception as exc:

        log.warning(
            "Could not connect to MongoDB: %s",
            exc,
        )

        log.info(
            "Predictions remain available in:\n%s",
            PRED_FILE,
        )

        log.info(
            "Start MongoDB using Docker before running the loader again."
        )

        # Return JSON-file information so the dashboard can still use
        # the prediction data through its fallback mechanism.
        return len(records), records[0]

    finally:

        if client is not None:

            client.close()

            log.info(
                "MongoDB connection closed."
            )


# ─────────────────────────────────────────────────────────────────────────────
# Script Entry Point
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    count, sample_document = load_predictions_to_mongo()

    print()
    print("=" * 60)
    print("MongoDB Loader Status")
    print("=" * 60)
    print(f"Prediction records ready : {count:,}")
    print(f"Database                 : {DB_NAME}")
    print(f"Collection               : {COLLECTION_NAME}")
    print("=" * 60)